server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          searchPaths: service1,service2
          # Private Git으로 username/password 필요
          uri: https://github.com/chanheejung/config-priv-repo/
          username: chanheejung
          password: "{cipher}2d6412a73ed441f4e9b9662a53a13ab5cd29435ece8dd6f6838b57db7c6cee4a"

          # Public Git으로 username/password 필요 없음
#          uri: https://github.com/chanheejung/config-repo/

        # File based Properties
#        native:
#          searchLocations: file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service1,
#            file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service2

management:
  endpoints:
    web:
      exposure:
        include: "*"