server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          searchPaths: service1,service2
          # Public Git으로 username/password 필요 없음
          uri: https://github.com/chanheejung/config-repo/
        # File based Properties
#        native:
#          searchLocations: file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service1,
#            file:///D:\devchan\MyStudy\SimpleMSA\config-server\src\main\resources\config\service2

management:
  endpoints:
    web:
      exposure:
        include: "*"